### ISSUE TITLE
babel "ReferenceError: Can't find variable: Symbol" when using 6to5 features

### ISSUE THREAD

**Issue by armhold** [josh/sprockets-es6#11]
Using Rails 4.2.0, sprockets 3.0.0.beta1 and sprockets-es6 0.6.0.

I'm unsure if this is a bug in sprockets, Babel, or simply user error. But the following snippet:
```
var m = new Map();
m.set('one', 1);

for (var x of m.values()) {
    console.log(x);
}

window.alert('hi');
```

gets translated into this:
```
"use strict";

var m = new Map();
m.set("one", 1);

for (var _iterator = m.values()[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
    var x = _step.value;

    console.log(x);
}

window.alert("hi");
```

which results in a "**ReferenceError: Can't find variable Symbol**".  From the [babel tracker](https://github.com/babel/babelify/issues/22), this looks like it might be a missing [polyfill](http://babeljs.io/docs/usage/caveats/).

**Comment by josh** [comment]
Try `#= require babel/polyfill`

**Comment by armhold** [comment]
Indeed, that solves it.  Thanks!
