### ISSUE TITLE
Automate concatenation requires

### ISSUE THREAD

**Issue by josh** [josh/sprockets-es6#12]
``` js
// app.js
//= require foo.js

// foo.js
import * as _ from "underscore";

// underscore.js
```

By default, I think app.js should have everything concatenated so you don't have to think about this. `app = underscore.js + foo.js + app.js`

Though, there still needs to be a better path for separating bundles.

``` js
// app.js
//= require foo.js

// foo.js
import d3 from "d3";

// d3.js
```

Where I want `app = foo.js + app.js` and have a separate `d3.js` thats loaded on demand.

This kinda ties into #8. Sprockets can help generate a mapping for all on demand bundles.

``` js
System.map['d3'] = 'assets/d3-abc123.js';
```

Maybe for now, lets just automatically mark any imported source as being "required" by the bundle. See how far that goes.

/cc @nfm

**Comment by nfm** [comment]
Awesome, sounds good to me @josh :)

I guess the concatenation best practices are slated to change once ES6 modules and HTTP/2 eventually become the standard, so flexibility will become more important over time. But in the meantime, I think the default you suggested is the best starting point.

**Comment by josh** [comment]
I'm working to get some APIs upstream to expose all imported ids.

https://github.com/babel/babel/pull/1031

Then we can automatically "require" all those here

**Comment by josh** [comment]
Still would like to do this, but blocked until babel exports that list of modules for us.
