### ISSUE TITLE
require directive and non-es6 assets

### ISSUE THREAD

**Issue by chancancode** [josh/sprockets-es6#18]
I was just trying this out this morning. I found this in the readme:

> Requires asset manifests for precompiling
> 
> .es6 won't work directly with config.assets.precompile = %w( foo.es6 ) for annoying compatibility
> reasons with Sprockets 2.x. Besides, you should look into moving away from config.assets.precompile > and using manifests instead. See Sprockets 3.x UPGRADING guide.

So, I added `app/manifest.js` and got that working (need a custom patch from @lucasmazza to make that working. Something like this:

```javascript
// app/manifest.js
//
//= link ./javascripts/application.es6
// ...
```

```javascript
// app/javascripts/application.es6
//
//= require jquery
// ...
```

...which is what the README suggested, if I understood it correctly. However, while I was able to get `application.es6` precompiled as expected, it couldn't find `jquery` from the require directive, because it is looking for something with the ES6 MIME type.

I ended up having to rename `application.es6` to `application.js`, which works (and I was able to require es6 dependencies from there), but it's kind of odd that I ended up having two manifest-looking things that has to be in `.js` extension.

1. Is this expected? Should we update the README to clarify it is the "root" file that you compile (whether through `config.assets.precompile` or through a manifest file) that has to be in `.js`?
2. Can we make this work?

**Comment by josh** [comment]
This "bug" should actually be fixed now as of https://github.com/rails/sprockets/pull/12

There might be some weird glob cases that breaks it but `config.assets.precompile = %w( foo.js )` where `foo.es6` exists should work now.

**Comment by chancancode** [comment]
Hm, I'm using master of everything this morning though. I'll push an app so you can take a look!

**Comment by josh** [comment]
```
//= link ./javascripts/application.es6
```

should be 

```
//= link ./javascripts/application.js
```

**Comment by chancancode** [comment]
Right, that's the "problem" I am reporting, and that's how I "fixed" it :smile:

What I am saying is that from the section of the README I quoted, I thought it is saying that `config.assets.precompile = %w( application.es6 )` won't work but `//= link ./javascripts/application.es6` would, but in fact the latter doesn't as you pointed out.

**Comment by chancancode** [comment]
(Related – does this also mean if you have an `application.coffee` or `application.scss` bundle, you can't require normal js/css from there?)

**Comment by chancancode** [comment]
Ping, is this a more generic "problem" that should be "fixed" (or wontfix'ed) upstream? (re: the last `.coffee` and `.scss` question)

**Comment by josh** [comment]
I'm still confused about what the latest example is not working.

The following mixing and matching should work.

``` js
// app/manifest.js
//
//= link ./javascripts/foo.js
//= link ./javascripts/bar.js
// ...
```

``` js
// app/javascripts/foo.es6
//
//= require jquery
```

``` coffee
# app/javascripts/bar.coffee
#
#= require jquery
```

``` js
// jquery.js
```

**Comment by chancancode** [comment]
AH, okay :smile:

I misunderstood your response. I thought I have to actually rename `app/javascripts/foo.es6` to `app/javascripts/foo.js` (and not use es6), which is what I did.

Tested that again and it works. Should we document that somewhere? It was not obvious to me at first :smile:

**Comment by chancancode** [comment]
(or, if we can make `//= link ./javascripts/foo.js` automagically work, that would be even nicer)

**Comment by josh** [comment]
> Should we document that somewhere?

For sure, I'd love to get more docs everywhere :wink: 

> (or, if we can make //= link ./javascripts/foo.js automagically work, that would be even nicer)

Did you mean `./javascripts/application.es6`?

The link stuff is special in that is doesn't inherit the content of the file you're in. By happy conscience `//= require ./javascripts/application.es6` should work inside an `.js` file since the `application/javascript` content type overrides whatever extension you passed to require. Sense only `application/javascript` can be combined with other `application/javascript`. You wouldn't concat a `foo.js` and foo.coffee` as is.

But linking doesn't inherit the current asset content type. This way you can link to an image from a css file. Or link to css from a js file. They aren't being combined so thats fine. The extension that you use is significant since you can now do `link foo.png` where foo.svg exists on disk and that could be transformed into a png.

I think everything is working correctly here, but I bet we could improve the error message. For the es6 example, I think its happening because its trying to concat a .js to an .es6 file and return .es6. That should be pretty detectable and easy to suggest what went wrong.

**Comment by chancancode** [comment]
> Did you mean ./javascripts/application.es6?

Oops, yes!

> By happy conscience //= require ./javascripts/application.es6 should work inside an .js file

That's also correct, it does in fact "work", the part that doesn't work is when it sees `//= require jquery` int the .es6 and tried to find `jquery.es6`, which does not exist

> I think everything is working correctly here

It makes sense now after reading the explanation! I think "you should put the final/output extension in the manifest" is fairly simple to learn and follow (but still it requires you to learn it)

> but I bet we could improve the error message

Yeah, it should probably blow up and suggest that you use `application.js`?
