### ISSUE TITLE
When using Sprockets 3.0.0.rc.2 with sprockets-es6, none of my assets are getting precompiled when changed

### ISSUE THREAD

**Issue by jonricaurte** [josh/sprockets-es6#21]
I am using the Systemjs module loader and have to include //= require above all my imports. When I change any of the files that are //= require, the assets are not precompiled so when I refresh in the browser, it shows old data. Currently I have to open rails console and use Rails.cache.clear and that works, but was wondering if there was a way where I did not have to do that?

Thanks.

**Comment by jonricaurte** [comment]
Looks like this is removed in sprockets 3.0. Closing.

**Comment by josh** [comment]
Its fixed, what was removed?

**Comment by jonricaurte** [comment]
Oops, I thought this was referencing the html files. Yes, this was fixed.
