### ISSUE TITLE
Decommission gem

### ISSUE THREAD

**Issue by josh** [josh/sprockets-es6#23]
Hey all,

I'm going to start trying to get everything here upstreamed in Sprockets 4.x at this point.

I don't personally want to maintain the 3.x plugin anyone. So anyone actually using this want to take it over?

@acconrad @BlakeWilliams @felixbuenemann @tricknotes @praxxis @TannerRogalsky @remiprev

**Comment by TannerRogalsky** [comment]
Yeah, [Uken](https://github.com/uken) would be happy to take over as maintainers of this gem. I can be the primary maintainer.

**Comment by josh** [comment]
@TannerRogalsky whats your rubygems email?

**Comment by josh** [comment]
You should also make a fork of this repository.

I'm going to delete my repo soon after.

**Comment by TannerRogalsky** [comment]
I've ensured that my fork of this repo is up to date with this one. My rubygems email is tanner@tannerrogalsky.com.

**Comment by josh** [comment]
@TannerRogalsky alright you should have push access.
