### ISSUE TITLE
Not compatible with therubyracer / v8

### ISSUE THREAD

**Issue by geofflane** [josh/sprockets-es6#4]
Include therubyracer gem in your gem file:
```
gem 'therubyracer', platforms: [:ruby]
```

When you reload the app you get a V8 error:
ActionView::Template::Error (Cannot set property 'to5' of undefined)

Remove therubyracer gem and it works. Probably deserves to be in the caveats section at least?

**Comment by josh** [comment]
https://github.com/6to5/ruby-6to5/commit/5c4fb5d5fbeadfc91ac5e3ca603718df69f85d99
