### ISSUE TITLE
ES6 Modules Support

### ISSUE THREAD

**Issue by felixbuenemann** [josh/sprockets-es6#6]
Please add a section to the README that describes how to use ES6 modules (import/export/require).

Currently it seems to compile down to CommonJS which is not that useful due to lack of support in browsers. There are several projects that provide es6 module transpilers for sprockets, but they also register for the es6 extension, so my guess is those can't be combined.

**Comment by josh** [comment]
No of the module stuff is implemented yet.

The final thing will likely be based on https://github.com/systemjs/systemjs rather than CommonJS specifically.

**Comment by felixbuenemann** [comment]
Thanks for the clarification, I also started experimenting with integrating system.js.

It would be nice if it was possible to pass options to the transformer. Currently `Sprockets::ES6.instance` simply calls `new` so it seems to be impossible to pass eg. `'modules' => 'system'` to `ES6to5.transform`.

**Comment by felixbuenemann** [comment]
Btw. for those interested in getting ES6 modules working using system.js, you can get it working in rails with a few monkey patches for sprockets-es6 to set the proper 6to5 transform options:

```ruby
# config/initializers/sprockets-es6-system-modules-patch.rb
require 'sprockets/es6'

module Sprockets
  class ES6
    def self.instance
      # monkey patch: set system js module style
      @instance ||= new('modules' => 'system', 'moduleIds' => true)
    end

    def call(input)
      data = input[:data]
      result = input[:cache].fetch(@cache_key + [data]) do
        # monkey patch: injected filename so module name is not "unknown"
        ES6to5.transform(data, @options.merge('filename' => input[:name]))
      end
      result['code']
    end
  end
end
```
Code for the [modules example](https://6to5.org/docs/learn-es6/#modules) from the 6to5 docs:
```javascript
// app/assets/javascripts/lib/math.es6
export function sum(x, y) {
  return x + y;
}
export var pi = 3.141593;

// app/assets/javascripts/application.es6
//= require es6-module-loader
//= require system
//= require_tree .

import * as math from "lib/math";
alert("2π = " + math.sum(math.pi, math.pi));
```
Execute the code from the application module:
```html
<!-- app/views/application.index.html -->
<script>System.import("application")</script>
```
Alternatively just use an application.js instead of .es6 and use `System.import` from there.

Note that no http requests are made by system.js if the modules have already been registered, so this works fine with sprockets fingerprinting.

My next step is to try this out with the [Aurelia Framework](http://aurelia.io) which fully embraces ES6 modules and syntax.

@josh I could come up with a PR, but I'm not sure what's the best place to set the options. Any ideas?

**Comment by josh** [comment]
That snippet actually looks pretty ideal to me.

Yeah, any modules should be able to be references by `input[:name]`. Thats going to be the correct module name.

> Note that no http requests are made by system.js if the modules have already been registered, so this works fine with sprockets fingerprinting.

:grinning: 

I'm thinking maybe sprockets-es6 bundles the `es6-module-loader.js` code itself. I'm not sure. I want to make sure people can easily update it on its own. Maybe just telling people to grab it externally is fine for now.

**Comment by felixbuenemann** [comment]
I would probably just tell people to grab it externally for now and make it possible to configure with module style to use. The default style could be ignore, which has no external dependencies and adds no wrapping around files.

If the default would be system.js modules, people might be surprised that their code is not available in the global namespace and there also might be users who just want to use eg. class syntax without modules.

**Comment by felixbuenemann** [comment]
If PR #7 gets merged it's possible to replace the monkey patch with some configuration of the sprockets environment, e.g. from `config/intializers/assets.rb` in rails:
```ruby
Rails.application.config.assets.configure do |env|
  env.register_transformer 'text/ecmascript-6', 'application/javascript',
    Sprockets::ES6.new('modules' => 'system', 'moduleIds' => true)
end
```

**Comment by josh** [comment]
Yeah, looks good.

**Comment by josh** [comment]
You might have some comments on another sprockets feature I'm working on for configuration.

https://github.com/sstephenson/sprockets/issues/667

The idea would be you could drop a `app/assets/.sprocketsconfig`

``` json
{ "6to5": { "modules": "system", "modulesIds": true }
```

And that'd just be scoped to `app/assets`. Or put it at the root to apply everywhere.

**Comment by felixbuenemann** [comment]
I like the idea, but I'm not sure if a config per directory is practical in this particular case. Let's say library A ships with one setting and library B with another, how would I override their setting in my app so they both use the same module syntax?

**Comment by josh** [comment]
> Let's say library A ships with one setting and library B with another

I don't think bower libraries should be including a sprocketsconfig. It'd mostly be to avoid processing application specific settings on vendor items.

**Comment by felixbuenemann** [comment]
In that case it should work fine.

**Comment by josh** [comment]
The main thing I was trying to say is that you could add `yourapp/.sprocketsconfig`

``` json
{ "6to5": { "modules": "system", "modulesIds": true }
```

instead of using the initializer configure block.

**Comment by nfm** [comment]
@felixbuenemann thanks for the write-up in your previous comments, that was super helpful :smile:

From playing around with this, it looks like you still need to use `require` or `require_tree` to make sure Sprockets includes the necessary files.

Is there an intention for having Sprockets piggy-back ES6's `import` statement to implicitly determine which scripts to require and concatenate, or is that a separate concern?

If these are separate issues, is there a sensible way to let SystemJS know the fingerprinted paths to files so that it can import them itself?

It would be great to not have to resort to `require_tree` and pull everything into a particular manifest, and to be able to avoid doubling up in each file like this:

```js
//= require math
import * as math from "lib/math";
```

**Comment by jonricaurte** [comment]
@felixbuenemann is it possible for you to share a sample repository on how to use everything together including the modules? Thanks!

**Comment by jonricaurte** [comment]
or  @nfm ?

**Comment by jonricaurte** [comment]
Actually I figured it out. Something was wrong with my environment.

**Comment by jonricaurte** [comment]
@nfm @josh @felixbuenemann I would actually suggest anyone using this pattern use:

//= require es6-module-loader
//= require system.js
//= require_tree .  

in their application.es6 because then you don't have to have //= require above every import in all your files.

**Comment by nfm** [comment]
@jonricaurte `require_tree` will do the trick, but only if you intend on having a single concatenated JS file to serve up (as opposed to multiple manifests, for example 'core.js', 'admin.js', 'libraries.js' etc.). And you may end up including files that are no longer imported anywhere - it's on the programmer to remember to delete them, rather than the build tool to know they're not in the dependency graph any more.

The latter probably isn't a big deal in practice, and you might not need multiple manifests, but they're the two drawbacks I've run into with `require_tree`.

**Comment by netikular** [comment]
@jonricaurte Would you be willing to put up that reference application.

I've tried several different ways to get this working in my application and I must be missing something as I never get to see the alert (using the example above).

**Comment by nfm** [comment]
Sorry all, should have posted this repo earlier: https://github.com/nfm/rails-es6-modules. This is how I got things working.

**Comment by jonricaurte** [comment]
@netikular Looks like @nfm has a good one to start with.

**Comment by netikular** [comment]
Thanks.  I'll give it a try.
