### ISSUE TITLE
Investigate first class SystemJS support

### ISSUE THREAD

**Issue by josh** [josh/sprockets-es6#8]
Its possible to configure 6to5 with AMD, CJS or SystemJS style module loading. All require a little bit of work to figure out.

Sprockets should have an out of the box configuration that just works if you really don't care. SystemJS is looking the best to me since its uses a ModuleLoader polyfill and has support for mixing and matching AMD and CJS. Should play well if your app is SystemJS and you install some AMD bower component.

https://github.com/systemjs/systemjs
https://github.com/ModuleLoader/es6-module-loader

**Comment by benlinton** [comment]
:+1: 

Maybe add a generator to create a rails initializer for configuring the module format: http://babeljs.io/docs/usage/modules/#formats ?

**Comment by josh** [comment]
You can already reregister the processor with custom options with

``` ruby
register_transformer 'text/ecmascript-6', 'application/javascript', ES6.new(module: "cjs")
```

I don't think its all that great, but I don't like the Rails init system either.

I'm looking for feedback on a sprockets config idea here https://github.com/sstephenson/sprockets/issues/667 Would like to hear what you think. It would make it a little easier to override these kinds of settings in apps.
