### ISSUE TITLE
`Sprockets::Manifest#compile` doesn't compile `.es6` file requiring `.js`

### ISSUE THREAD

**Issue by tricknotes** [josh/sprockets-es6#9]
When `.es6` file includes `require` directive for `.js`, `Sprockets::Manifest#compile` doesn't work caused by MIME Type mismatch. 
(It seems the `require` directive would resolve dependency as `text/ecmascript-6`.)

My repro code is [here](https://github.com/tricknotes/sprockets-es6-issue-9).

The following patch seems to work well for me.

``` diff
diff --git a/lib/sprockets/es6.rb b/lib/sprockets/es6.rb
index 555184f..7f7749d 100644
--- a/lib/sprockets/es6.rb
+++ b/lib/sprockets/es6.rb
@@ -38,7 +38,5 @@ module Sprockets
   end
 
   append_path ES6to5::Source.root
-  register_mime_type 'text/ecmascript-6', extensions: ['.es6'], charset: :unicode
-  register_transformer 'text/ecmascript-6', 'application/javascript', ES6
-  register_preprocessor 'text/ecmascript-6', DirectiveProcessor
+  register_engine '.es6', ES6, mime_type: 'application/javascript'
 end
```

But I'm not sure whether this way is good or bad.
Are there any reason `register_engine` is not used?

**Comment by tricknotes** [comment]
Ah, this configuration makes it disabled that `.js` can require `.es6`...

**Comment by josh** [comment]
> Are there any reason register_engine is not used?

The engine stuff is deprecated and won't be in 4.x. We *could* still use engine here, but I was hoping to use this as a testing grounds to work out the bugs on engine v transformer interop. So maybe you found one of those bugs ;)

**Comment by praxxis** [comment]
I've worked around this with a pretty horrible hack:
```ruby
# Sprockets knows that ES6 transforms to JS, but not vice-versa, which means that it is unable to `require`
# a JS file from within an ES6 file. However, you can supply a composite mime type, which Sprockets will
# use as a type of "accepts" field.
Kickstarter::Application.assets.register_mime_type 'text/ecmascript-6,application/javascript', extensions: ['.es6'], charset: :unicode
Kickstarter::Application.assets.register_transformer 'text/ecmascript-6,application/javascript', 'application/javascript', Sprockets::ES6.new()
Kickstarter::Application.assets.register_preprocessor 'text/ecmascript-6,application/javascript', Sprockets::DirectiveProcessor
```

You can trick Sprockets into accepting both `.es6` and `.js` as JavaScript by registering a weird composite mime type. See [here](https://github.com/sstephenson/sprockets/blob/faceba518a866aee4c454775112a578e2f3ff166/lib/sprockets/http_utils.rb#L26) and [here](https://github.com/sstephenson/sprockets/blob/c87b899e15e9944baee43af3c5ff9d2edd7e4142/lib/sprockets/resolve.rb#L122)

**Comment by josh** [comment]
@praxxis ha, well, that sounds like a bug that it let you do that. There probably should be some sort of validation `raise` there.

**Comment by josh** [comment]
Alright, sorry this took so long but I figured it out. Unfortunately its an issue with `Manifest.compile` itself and needs to work a certain way for compatibility with 2.x  It will work as expected in 4.x so it won't be a problem when Babel is built into Sprockets. I added a test for this https://github.com/rails/sprockets/commit/2d98f95f35d9d8e4877717168bf1e0ca83c40cb6

For now I added a note to the readme about the caveat. https://github.com/josh/sprockets-es6/commit/b396342f18e424e044085d0e8f65b76f73164796

Theres a few work arounds. The preferred is to avoid the complications of `Manifest.compile` and use the compile manifest stuff and only compile a single `Manifest.compile("manifest.js")`. Or you can simply make sure that whatever you are directly passing into `Manifest.compile` is a regular `.js` file. Any of the dependencies can be `.es6` and that will work fine. Its only an issue with the direct file passed to that function.

Thanks for reporting!
